CREATE TABLE USER (
USER_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(20) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
SALT VARCHAR(20) NOT NULL,
DESCRIPTIONS VARCHAR(255)
)

CREATE TABLE ROLE(
ROLE_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(20) NOT NULL UNIQUE,
DESCRIPTIONS VARCHAR(255)
)

CREATE TABLE PERMISSION(
PERMISSION_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
PERMISSION_NAME VARCHAR(20) NOT NULL UNIQUE,
DESCRIPTIONS VARCHAR(255)
)

CREATE TABLE USER_ROLE(
USER_ID BIGINT(20) NOT NULL,
ROLE_ID BIGINT(20) NOT NULL,
PRIMARY KEY(USER_ID,ROLE_ID),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE ROLE_PERMISSION(
ROLE_ID BIGINT(20) NOT NULL,
PERMISSION_ID BIGINT(20) NOT NULL,
PRIMARY KEY(ROLE_ID,PERMISSION_ID),
FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(PERMISSION_ID) REFERENCES PERMISSION(PERMISSION_ID)
ON DELETE CASCADE ON UPDATE CASCADE
)