spring:
  # 配置sql的数据库连接池
  datasource:
    # 基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 其他配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 主数据源
      master:
        username: root
        password: QTSS.a000
        url: jdbc:mysql://localhost:3306/message
      # 从数据源
      slave:
        enabled: false # 默认从数据库是关闭的
        url: jdbc:mysql://localhost:3306/message
        username: root
        password: QTSS.a000

      # 初始连接数为5
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取配置最大等待时间
      max-wait: 60000
      # 隔多久检查一次配置信息，关闭空闲的连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在连接池中最小生存时间
      min-evictable-idle-time-millis: 30000
      # 一个连接在连接池中最大生存时间
      max-evictable-idle-time-millis: 90000
      # 获取连接时检测，会影响性能
      test-on-borrow: false
      # 申请连接时检测，不会影响性能
      test-while-idle: true
      # 归还连接时检测，归还连接时的检测
      test-on-return: false
      # 用于对数据库的检测采用什么方法
      validation-query: SELECT 1 from DUAL
